### ISSUE TITLE
Feature request: read icon

### ISSUE THREAD

**Issue by mebibou** [openstf/adbkit-apkreader#8]
Is it possible to use this library to retrieve the icon? I guess knowing the path using `usingFileStream ()` would work but how to get the path?

**Comment by sorccu** [comment]
Currently it isn't possible because we didn't need the functionality to retrieve resources. However, you don't necessarily even need an APK parser to retrieve the icon. You could just use a zip parser and try to find the icon file that way. Obviously the path may change per app but it's probably going to be relatively easily detectable anyway.

**Comment by mebibou** [comment]
Oh actually that's even easier:
```
exec('aapt d --values badging ' + file, function(error, stdout, stderr) {
  var icon = stdout.match(/icon='(.*)'/)[1];

  ApkReader.open(filePath).then(function(reader) {
    return reader.readContent(icon);
  }).then(function(data) {
    fs.writeFile('icon.png', data, 'binary');
  });
});
```
